# Generated by Django 6.0.3 on 2026-03-10 11:34

import django.core.validators
import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=20, unique=True)),
                ('airline_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('seats_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('aircraft_type', models.CharField(choices=[('Boeing 737', 'Boeing 737'), ('Boeing 747', 'Boeing 747'), ('Airbus A320', 'Airbus A320'), ('Airbus A380', 'Airbus A380')], default='Boeing 737', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Flights',
                'ordering': ['departure_time'],
                'indexes': [models.Index(fields=['flight_id'], name='flights_fli_flight__5aaf6d_idx'), models.Index(fields=['departure_time'], name='flights_fli_departu_5bc2af_idx'), models.Index(fields=['source', 'destination'], name='flights_fli_source_c16590_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flights.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'flight')},
            },
        ),
    ]
